const express = require('express')
const router = express.Router()
const jwtServices = require("../services/jwt.service")
const { checkRole } = require('../middleware/checkRole.middleware')
const Controller = require('../controllers/Admin.controller')
const Validate = require("../validators/index")
const { defaultRoles } = require('../config/defineModel')
const SchemaValidateAdmin = require("../validators/admin.validator")

router.post('/createUserAdmin', jwtServices.verify, checkRole([defaultRoles.Admin]), Validate.body(SchemaValidateAdmin.createUser), Controller.createUserAsync)
router.post('/loginAdmin', Validate.body(SchemaValidateAdmin.loginUser), Controller.loginAsync)
router.get('/quantityStatisticsAdmin', jwtServices.verify, checkRole([defaultRoles.Admin]), Controller.quantityStatisticsAdminAsync)
router.get('/statisticsBillAdmin', jwtServices.verify, checkRole([defaultRoles.Admin]), Controller.statisticsBillAdminAsync)
router.get('/getBestSellProductAdmin', jwtServices.verify, checkRole([defaultRoles.Admin]), Controller.getBestSellProductAdminAsync)
router.get('/statisticsReviewAdmin', jwtServices.verify, checkRole([defaultRoles.Admin]), Controller.statisticsReviewAdminAsync)
router.get('/getReviewNewAdmin', jwtServices.verify, checkRole([defaultRoles.Admin]), Controller.getReviewNewAdminAsync)
router.get('/getStatisticsSellAdmin', jwtServices.verify, checkRole([defaultRoles.Admin]), Controller.getStatisticsSellAdminAsync)
module.exports = router